name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: paulovanzolini
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: devops/Dockerfile
          target: app
          tags: paulovanzolini/bora:frontend-${{ steps.extract_branch.outputs.branch }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Start Deployment
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ec2-3-84-165-44.compute-1.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_BORA_PEM }}
        port: 22
        script: ./deploy.sh
